language: go
go:
  - 1.13.x

before_install:
  - go install github.com/rakyll/statik github.com/golang/mock/mockgen
  - go get -t -v ./...

script:
  - make
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
